"""add_ai_fields_to_medical_records

Revision ID: 6d4eea24f074
Revises: b6055588384e
Create Date: 2026-06-15 10:17:50.264575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4eea24f074'
down_revision: Union[str, Sequence[str], None] = 'b6055588384e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('is_pneumonia', sa.Boolean(), nullable=True))
    op.add_column('medical_records', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('medical_records', sa.Column('ai_model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'ai_model')
    op.drop_column('medical_records', 'confidence')
    op.drop_column('medical_records', 'is_pneumonia')
    # ### end Alembic commands ###
